os: osx
osx_image: xcode9.3
language: swift
xcode_project: NearBy.xcodeproj
xcode_sdk: iphonesimulator
script:
- xcodebuild clean build test -workspace NearBy/NearBy.xcworkspace -scheme "NearBy" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=9.3,name=iPhone8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

